### ISSUE TITLE
Graphics 용어에 대하여

### ISSUE THREAD

**Issue by JinSungYoon** [18-1-SKKU-OSS/2018-1-OSS-L7#5]
번역을 하던중에 Grahpics 용어가 많이 나오는데 이것을 직역해야 할까요? 아니면 그 용어는 그대로 사용할까요???

**Comment by talunhahwe** [comment]
어떤 용어를 말하시는지 모르겠지만 일단 vertex, texture 같은 용어는 버텍스, 텍스쳐 등으로 번역해두시는게 나중에 검수하더라도 편할 것 같습니다.

**Comment by JinSungYoon** [comment]
Fragment shading이나 fragmentColor vertex shading같이 뭔가 직역하면 이상한게 있어서 그랬는데 일단 검수를 위해서 프래그먼트 쉐이딩 같이 통일하겠습니다.
